development:
  adapter: postgresql
  database: callmom_development
  username: Ajay
  password: goenso
  host: localhost
  port: 5432
  timeout: 5000

production:
  adapter: postgresql
  database: callmom_production
  username: Ajay
  password: goenso
  host: localhost
  port: 5432
  timeout: 5000
